CREATE DATABASE TaskManagerDB;

USE TaskManagerDB;

CREATE TABLE users(
	userId INT PRIMARY KEY IDENTITY(1,1),
	userName VARCHAR(150) UNIQUE NOT NULL,
	email VARCHAR(100) NOT NULL,
	password VARCHAR(200)
);

CREATE TABLE tasks(
	taskId INT PRIMARY KEY IDENTITY(1,1),
	userId INT FOREIGN KEY REFERENCES users(userId),
	title VARCHAR(200) NOT NULL,
	taskContent VARCHAR(200) NOT NULL,
	createdAt DATETIME2 DEFAULT GETDATE()
);

CREATE TABLE notes(
	notesId INT PRIMARY KEY IDENTITY(1,1),
	taskId INT FOREIGN KEY REFERENCES tasks(taskId),
	userId INT FOREIGN KEY REFERENCES users(userId),
	content VARCHAR(200),
	createdAt DATETIME2 DEFAULT GETDATE()
);

SELECT * FROM tasks;
SELECT * FROM notes;
SELECT * FROM users;